name = "DemeNet"
uuid = "311d44f8-95d5-40c8-b71c-a916d7747227"
authors = ["akels <akels14@gmail.com>"]
version = "0.1.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1"

[extras]
PeaceCypher = "7743456c-e0c5-4477-a2b6-196c240b0368"

[targets]
test = ["PeaceCypher"]
